-- +goose Up
-- +goose StatementBegin



-- Punya api_key → akan di-generate bersamaan dengan tenant ID
-- Bisa punya relasi ke external system (KYC provider, payment gateway)
-- Ada hierarchical relationship (parent_tenant_id)
-- Audit trail penting (siapa create tenant, kapan)

-- Tenants are B2B clients (e-commerce platforms, sellers, corporate treasury)
CREATE TABLE tenants (
    id                      UUID PRIMARY KEY NOT NULL,  -- No DEFAULT, app generates
    display_name            VARCHAR(100) NOT NULL,
    legal_name              VARCHAR(200) NOT NULL,
    country                 CHAR(2) NOT NULL,
    tenant_kind             tenant_kind_enum NOT NULL,
    -- Parent tenant for hierarchical relationships (platform -> sellers)
    parent_tenant_id        UUID REFERENCES tenants(id),
    -- Legal entity this tenant is assigned to
    legal_entity_id         UUID NOT NULL REFERENCES legal_entities(id),
    -- Status and verification
    tenant_status           tenant_status_enum NOT NULL DEFAULT 'pending_kyc',
    kyc_level               kyc_level_enum NOT NULL DEFAULT 'basic',
    -- Netting configuration
    netting_enabled         BOOLEAN NOT NULL DEFAULT false,
    netting_window_minutes  INTEGER NOT NULL DEFAULT 5,
    -- API access
    api_key_hash            VARCHAR(64),
    webhook_url             VARCHAR(500),
    webhook_secret_hash     VARCHAR(64),
    -- Metadata
    metadata                JSONB NOT NULL DEFAULT '{}',
    -- Timestamps
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_connected_parent
        CHECK ( 
            tenant_kind != 'connected'
            OR parent_tenant_id IS NOT NULL
        )
);

CREATE TABLE tenant_capabilities (
    tenant_id           UUID PRIMARY KEY REFERENCES tenants(id),
    can_have_children   BOOLEAN NOT NULL DEFAULT false,
    can_netting         BOOLEAN NOT NULL DEFAULT false,
    can_batch_transfer  BOOLEAN NOT NULL DEFAULT false,
    fees_responsibility TEXT NOT NULL DEFAULT 'platform',  -- 'platform' | 'tenant'
    kyc_tier            TEXT NOT NULL DEFAULT 'basic',     -- 'basic' | 'standard' | 'enhanced'
    dashboard_access    TEXT NOT NULL DEFAULT 'none',      -- 'full' | 'limited' | 'none'
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN tenants.id IS 
    'UUID v7 generated by application layer. Required for API key generation and external system correlation.';

-- Indexes for common queries
CREATE INDEX idx_tenants_legal_entity ON tenants(legal_entity_id);
CREATE INDEX idx_tenants_parent ON tenants(parent_tenant_id) WHERE parent_tenant_id IS NOT NULL;
CREATE INDEX idx_tenants_status ON tenants(tenant_status) WHERE tenant_status = 'active';
CREATE INDEX idx_tenants_kind ON tenants(tenant_kind);
CREATE INDEX idx_tenants_country ON tenants(country);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS tenants;

-- +goose StatementEnd
