// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: legal_entities.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getLegalEntityByCode = `-- name: GetLegalEntityByCode :one
SELECT id, code, legal_name, jurisdiction, license_type, license_number, regulator,
    fbo_bank_name, fbo_account_iban, fbo_account_number, fbo_sort_code,
    nostro_bank_name, nostro_account_iban, nostro_account_number, nostro_sort_code,
    supported_currencies, supported_rails, updated_at
FROM legal_entities
WHERE code = $1
`

func (q *Queries) GetLegalEntityByCode(ctx context.Context, code string) (LegalEntity, error) {
	row := q.db.QueryRow(ctx, getLegalEntityByCode, code)
	var i LegalEntity
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LegalName,
		&i.Jurisdiction,
		&i.LicenseType,
		&i.LicenseNumber,
		&i.Regulator,
		&i.FboBankName,
		&i.FboAccountIban,
		&i.FboAccountNumber,
		&i.FboSortCode,
		&i.NostroBankName,
		&i.NostroAccountIban,
		&i.NostroAccountNumber,
		&i.NostroSortCode,
		&i.SupportedCurrencies,
		&i.SupportedRails,
		&i.UpdatedAt,
	)
	return i, err
}

const getLegalEntityByID = `-- name: GetLegalEntityByID :one
SELECT id, code, legal_name, jurisdiction, license_type, license_number, regulator,
    fbo_bank_name, fbo_account_iban, fbo_account_number, fbo_sort_code,
    nostro_bank_name, nostro_account_iban, nostro_account_number, nostro_sort_code,
    supported_currencies, supported_rails, updated_at
FROM legal_entities
WHERE id = $1
`

func (q *Queries) GetLegalEntityByID(ctx context.Context, id uuid.UUID) (LegalEntity, error) {
	row := q.db.QueryRow(ctx, getLegalEntityByID, id)
	var i LegalEntity
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LegalName,
		&i.Jurisdiction,
		&i.LicenseType,
		&i.LicenseNumber,
		&i.Regulator,
		&i.FboBankName,
		&i.FboAccountIban,
		&i.FboAccountNumber,
		&i.FboSortCode,
		&i.NostroBankName,
		&i.NostroAccountIban,
		&i.NostroAccountNumber,
		&i.NostroSortCode,
		&i.SupportedCurrencies,
		&i.SupportedRails,
		&i.UpdatedAt,
	)
	return i, err
}

const listLegalEntities = `-- name: ListLegalEntities :many
SELECT id, code, legal_name, jurisdiction, license_type, license_number, regulator,
    fbo_bank_name, fbo_account_iban, fbo_account_number, fbo_sort_code,
    nostro_bank_name, nostro_account_iban, nostro_account_number, nostro_sort_code,
    supported_currencies, supported_rails, updated_at
FROM legal_entities
ORDER BY code
`

func (q *Queries) ListLegalEntities(ctx context.Context) ([]LegalEntity, error) {
	rows, err := q.db.Query(ctx, listLegalEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegalEntity{}
	for rows.Next() {
		var i LegalEntity
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.LegalName,
			&i.Jurisdiction,
			&i.LicenseType,
			&i.LicenseNumber,
			&i.Regulator,
			&i.FboBankName,
			&i.FboAccountIban,
			&i.FboAccountNumber,
			&i.FboSortCode,
			&i.NostroBankName,
			&i.NostroAccountIban,
			&i.NostroAccountNumber,
			&i.NostroSortCode,
			&i.SupportedCurrencies,
			&i.SupportedRails,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalEntitiesByJurisdiction = `-- name: ListLegalEntitiesByJurisdiction :many
SELECT id, code, legal_name, jurisdiction, license_type, license_number, regulator,
    fbo_bank_name, fbo_account_iban, fbo_account_number, fbo_sort_code,
    nostro_bank_name, nostro_account_iban, nostro_account_number, nostro_sort_code,
    supported_currencies, supported_rails, updated_at
FROM legal_entities
WHERE jurisdiction = $1
ORDER BY code
`

func (q *Queries) ListLegalEntitiesByJurisdiction(ctx context.Context, jurisdiction string) ([]LegalEntity, error) {
	rows, err := q.db.Query(ctx, listLegalEntitiesByJurisdiction, jurisdiction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegalEntity{}
	for rows.Next() {
		var i LegalEntity
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.LegalName,
			&i.Jurisdiction,
			&i.LicenseType,
			&i.LicenseNumber,
			&i.Regulator,
			&i.FboBankName,
			&i.FboAccountIban,
			&i.FboAccountNumber,
			&i.FboSortCode,
			&i.NostroBankName,
			&i.NostroAccountIban,
			&i.NostroAccountNumber,
			&i.NostroSortCode,
			&i.SupportedCurrencies,
			&i.SupportedRails,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
