// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type KycLevelEnum string

const (
	KycLevelEnumBasic    KycLevelEnum = "basic"
	KycLevelEnumStandard KycLevelEnum = "standard"
	KycLevelEnumEnhanced KycLevelEnum = "enhanced"
)

func (e *KycLevelEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KycLevelEnum(s)
	case string:
		*e = KycLevelEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for KycLevelEnum: %T", src)
	}
	return nil
}

type NullKycLevelEnum struct {
	KycLevelEnum KycLevelEnum `json:"kyc_level_enum"`
	Valid        bool         `json:"valid"` // Valid is true if KycLevelEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKycLevelEnum) Scan(value interface{}) error {
	if value == nil {
		ns.KycLevelEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KycLevelEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKycLevelEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KycLevelEnum), nil
}

type LicenseTypeEnum string

const (
	LicenseTypeEnumEMI  LicenseTypeEnum = "EMI"
	LicenseTypeEnumPI   LicenseTypeEnum = "PI"
	LicenseTypeEnumBANK LicenseTypeEnum = "BANK"
)

func (e *LicenseTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LicenseTypeEnum(s)
	case string:
		*e = LicenseTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for LicenseTypeEnum: %T", src)
	}
	return nil
}

type NullLicenseTypeEnum struct {
	LicenseTypeEnum LicenseTypeEnum `json:"license_type_enum"`
	Valid           bool            `json:"valid"` // Valid is true if LicenseTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLicenseTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.LicenseTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LicenseTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLicenseTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LicenseTypeEnum), nil
}

type RailEnum string

const (
	RailEnumSEPAINSTANT RailEnum = "SEPA_INSTANT"
	RailEnumSEPASCT     RailEnum = "SEPA_SCT"
	RailEnumFPS         RailEnum = "FPS"
	RailEnumCHAPS       RailEnum = "CHAPS"
	RailEnumBIFAST      RailEnum = "BI_FAST"
	RailEnumRTGS        RailEnum = "RTGS"
	RailEnumSWIFT       RailEnum = "SWIFT"
)

func (e *RailEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RailEnum(s)
	case string:
		*e = RailEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RailEnum: %T", src)
	}
	return nil
}

type NullRailEnum struct {
	RailEnum RailEnum `json:"rail_enum"`
	Valid    bool     `json:"valid"` // Valid is true if RailEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRailEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RailEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RailEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRailEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RailEnum), nil
}

type TenantKindEnum string

const (
	TenantKindEnumPlatform TenantKindEnum = "platform"
	TenantKindEnumSeller   TenantKindEnum = "seller"
	TenantKindEnumDirect   TenantKindEnum = "direct"
)

func (e *TenantKindEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantKindEnum(s)
	case string:
		*e = TenantKindEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantKindEnum: %T", src)
	}
	return nil
}

type NullTenantKindEnum struct {
	TenantKindEnum TenantKindEnum `json:"tenant_kind_enum"`
	Valid          bool           `json:"valid"` // Valid is true if TenantKindEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantKindEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TenantKindEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantKindEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantKindEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantKindEnum), nil
}

type TenantStatusEnum string

const (
	TenantStatusEnumPendingKyc TenantStatusEnum = "pending_kyc"
	TenantStatusEnumActive     TenantStatusEnum = "active"
	TenantStatusEnumSuspended  TenantStatusEnum = "suspended"
	TenantStatusEnumClosed     TenantStatusEnum = "closed"
)

func (e *TenantStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatusEnum(s)
	case string:
		*e = TenantStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatusEnum: %T", src)
	}
	return nil
}

type NullTenantStatusEnum struct {
	TenantStatusEnum TenantStatusEnum `json:"tenant_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if TenantStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatusEnum), nil
}

type TransferStatusEnum string

const (
	TransferStatusEnumCreated    TransferStatusEnum = "created"
	TransferStatusEnumValidating TransferStatusEnum = "validating"
	TransferStatusEnumRejected   TransferStatusEnum = "rejected"
	TransferStatusEnumProcessing TransferStatusEnum = "processing"
	TransferStatusEnumCompleted  TransferStatusEnum = "completed"
	TransferStatusEnumRolledBack TransferStatusEnum = "rolled_back"
	TransferStatusEnumCancelled  TransferStatusEnum = "cancelled"
)

func (e *TransferStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferStatusEnum(s)
	case string:
		*e = TransferStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferStatusEnum: %T", src)
	}
	return nil
}

type NullTransferStatusEnum struct {
	TransferStatusEnum TransferStatusEnum `json:"transfer_status_enum"`
	Valid              bool               `json:"valid"` // Valid is true if TransferStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TransferStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferStatusEnum), nil
}

type LegalEntity struct {
	ID                  uuid.UUID       `json:"id"`
	Code                string          `json:"code"`
	LegalName           string          `json:"legal_name"`
	Jurisdiction        string          `json:"jurisdiction"`
	LicenseType         LicenseTypeEnum `json:"license_type"`
	LicenseNumber       pgtype.Text     `json:"license_number"`
	Regulator           pgtype.Text     `json:"regulator"`
	FboBankName         pgtype.Text     `json:"fbo_bank_name"`
	FboAccountIban      pgtype.Text     `json:"fbo_account_iban"`
	FboAccountNumber    pgtype.Text     `json:"fbo_account_number"`
	FboSortCode         pgtype.Text     `json:"fbo_sort_code"`
	NostroBankName      pgtype.Text     `json:"nostro_bank_name"`
	NostroAccountIban   pgtype.Text     `json:"nostro_account_iban"`
	NostroAccountNumber pgtype.Text     `json:"nostro_account_number"`
	NostroSortCode      pgtype.Text     `json:"nostro_sort_code"`
	SupportedCurrencies []string        `json:"supported_currencies"`
	SupportedRails      []RailEnum      `json:"supported_rails"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

type LimitPolicy struct {
	ID                  uuid.UUID      `json:"id"`
	TenantID            uuid.UUID      `json:"tenant_id"`
	DailyLimitUsd       pgtype.Numeric `json:"daily_limit_usd"`
	MonthlyLimitUsd     pgtype.Numeric `json:"monthly_limit_usd"`
	PerTransferLimitUsd pgtype.Numeric `json:"per_transfer_limit_usd"`
	RateLimitRpm        int32          `json:"rate_limit_rpm"`
	RateLimitBurst      int32          `json:"rate_limit_burst"`
	MaxBatchSize        int32          `json:"max_batch_size"`
	MaxBatchAmountUsd   pgtype.Numeric `json:"max_batch_amount_usd"`
	EffectiveFrom       pgtype.Date    `json:"effective_from"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type PricingPolicy struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	FxMarginBps       int32              `json:"fx_margin_bps"`
	FeeStructure      []byte             `json:"fee_structure"`
	CorridorOverrides []byte             `json:"corridor_overrides"`
	ValidFrom         time.Time          `json:"valid_from"`
	ValidUntil        pgtype.Timestamptz `json:"valid_until"`
}

type Tenant struct {
	ID                   uuid.UUID        `json:"id"`
	DisplayName          string           `json:"display_name"`
	LegalName            string           `json:"legal_name"`
	Country              string           `json:"country"`
	TenantKind           TenantKindEnum   `json:"tenant_kind"`
	ParentTenantID       pgtype.UUID      `json:"parent_tenant_id"`
	LegalEntityID        uuid.UUID        `json:"legal_entity_id"`
	TenantStatus         TenantStatusEnum `json:"tenant_status"`
	KycLevel             KycLevelEnum     `json:"kyc_level"`
	NettingEnabled       bool             `json:"netting_enabled"`
	NettingWindowMinutes int32            `json:"netting_window_minutes"`
	ApiKeyHash           pgtype.Text      `json:"api_key_hash"`
	WebhookUrl           pgtype.Text      `json:"webhook_url"`
	WebhookSecretHash    pgtype.Text      `json:"webhook_secret_hash"`
	Metadata             []byte           `json:"metadata"`
	UpdatedAt            time.Time        `json:"updated_at"`
}

type Transfer struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	SourceLegalEntityID pgtype.UUID        `json:"source_legal_entity_id"`
	DestLegalEntityID   pgtype.UUID        `json:"dest_legal_entity_id"`
	QuoteID             pgtype.UUID        `json:"quote_id"`
	BatchID             pgtype.UUID        `json:"batch_id"`
	RecipientID         pgtype.UUID        `json:"recipient_id"`
	IdempotencyKey      pgtype.Text        `json:"idempotency_key"`
	FromCurrency        string             `json:"from_currency"`
	ToCurrency          string             `json:"to_currency"`
	FromAmount          pgtype.Numeric     `json:"from_amount"`
	ToAmount            pgtype.Numeric     `json:"to_amount"`
	FxRate              pgtype.Numeric     `json:"fx_rate"`
	TotalFee            pgtype.Numeric     `json:"total_fee"`
	Status              TransferStatusEnum `json:"status"`
	FailureReason       pgtype.Text        `json:"failure_reason"`
	Rail                NullRailEnum       `json:"rail"`
	RailReference       pgtype.Text        `json:"rail_reference"`
	NettingGroupID      pgtype.UUID        `json:"netting_group_id"`
	IsNetted            bool               `json:"is_netted"`
	TbTransferIds       []pgtype.Numeric   `json:"tb_transfer_ids"`
	RiskScore           pgtype.Int4        `json:"risk_score"`
	ComplianceStatus    string             `json:"compliance_status"`
	ScreenedAt          pgtype.Timestamptz `json:"screened_at"`
	ComplianceRegion    string             `json:"compliance_region"`
	UpdatedAt           time.Time          `json:"updated_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

type TransfersEu struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	SourceLegalEntityID pgtype.UUID        `json:"source_legal_entity_id"`
	DestLegalEntityID   pgtype.UUID        `json:"dest_legal_entity_id"`
	QuoteID             pgtype.UUID        `json:"quote_id"`
	BatchID             pgtype.UUID        `json:"batch_id"`
	RecipientID         pgtype.UUID        `json:"recipient_id"`
	IdempotencyKey      pgtype.Text        `json:"idempotency_key"`
	FromCurrency        string             `json:"from_currency"`
	ToCurrency          string             `json:"to_currency"`
	FromAmount          pgtype.Numeric     `json:"from_amount"`
	ToAmount            pgtype.Numeric     `json:"to_amount"`
	FxRate              pgtype.Numeric     `json:"fx_rate"`
	TotalFee            pgtype.Numeric     `json:"total_fee"`
	Status              TransferStatusEnum `json:"status"`
	FailureReason       pgtype.Text        `json:"failure_reason"`
	Rail                NullRailEnum       `json:"rail"`
	RailReference       pgtype.Text        `json:"rail_reference"`
	NettingGroupID      pgtype.UUID        `json:"netting_group_id"`
	IsNetted            bool               `json:"is_netted"`
	TbTransferIds       []pgtype.Numeric   `json:"tb_transfer_ids"`
	RiskScore           pgtype.Int4        `json:"risk_score"`
	ComplianceStatus    string             `json:"compliance_status"`
	ScreenedAt          pgtype.Timestamptz `json:"screened_at"`
	ComplianceRegion    string             `json:"compliance_region"`
	UpdatedAt           time.Time          `json:"updated_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

type TransfersID struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	SourceLegalEntityID pgtype.UUID        `json:"source_legal_entity_id"`
	DestLegalEntityID   pgtype.UUID        `json:"dest_legal_entity_id"`
	QuoteID             pgtype.UUID        `json:"quote_id"`
	BatchID             pgtype.UUID        `json:"batch_id"`
	RecipientID         pgtype.UUID        `json:"recipient_id"`
	IdempotencyKey      pgtype.Text        `json:"idempotency_key"`
	FromCurrency        string             `json:"from_currency"`
	ToCurrency          string             `json:"to_currency"`
	FromAmount          pgtype.Numeric     `json:"from_amount"`
	ToAmount            pgtype.Numeric     `json:"to_amount"`
	FxRate              pgtype.Numeric     `json:"fx_rate"`
	TotalFee            pgtype.Numeric     `json:"total_fee"`
	Status              TransferStatusEnum `json:"status"`
	FailureReason       pgtype.Text        `json:"failure_reason"`
	Rail                NullRailEnum       `json:"rail"`
	RailReference       pgtype.Text        `json:"rail_reference"`
	NettingGroupID      pgtype.UUID        `json:"netting_group_id"`
	IsNetted            bool               `json:"is_netted"`
	TbTransferIds       []pgtype.Numeric   `json:"tb_transfer_ids"`
	RiskScore           pgtype.Int4        `json:"risk_score"`
	ComplianceStatus    string             `json:"compliance_status"`
	ScreenedAt          pgtype.Timestamptz `json:"screened_at"`
	ComplianceRegion    string             `json:"compliance_region"`
	UpdatedAt           time.Time          `json:"updated_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

type TransfersUk struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	SourceLegalEntityID pgtype.UUID        `json:"source_legal_entity_id"`
	DestLegalEntityID   pgtype.UUID        `json:"dest_legal_entity_id"`
	QuoteID             pgtype.UUID        `json:"quote_id"`
	BatchID             pgtype.UUID        `json:"batch_id"`
	RecipientID         pgtype.UUID        `json:"recipient_id"`
	IdempotencyKey      pgtype.Text        `json:"idempotency_key"`
	FromCurrency        string             `json:"from_currency"`
	ToCurrency          string             `json:"to_currency"`
	FromAmount          pgtype.Numeric     `json:"from_amount"`
	ToAmount            pgtype.Numeric     `json:"to_amount"`
	FxRate              pgtype.Numeric     `json:"fx_rate"`
	TotalFee            pgtype.Numeric     `json:"total_fee"`
	Status              TransferStatusEnum `json:"status"`
	FailureReason       pgtype.Text        `json:"failure_reason"`
	Rail                NullRailEnum       `json:"rail"`
	RailReference       pgtype.Text        `json:"rail_reference"`
	NettingGroupID      pgtype.UUID        `json:"netting_group_id"`
	IsNetted            bool               `json:"is_netted"`
	TbTransferIds       []pgtype.Numeric   `json:"tb_transfer_ids"`
	RiskScore           pgtype.Int4        `json:"risk_score"`
	ComplianceStatus    string             `json:"compliance_status"`
	ScreenedAt          pgtype.Timestamptz `json:"screened_at"`
	ComplianceRegion    string             `json:"compliance_region"`
	UpdatedAt           time.Time          `json:"updated_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

type TransfersUnknown struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	SourceLegalEntityID pgtype.UUID        `json:"source_legal_entity_id"`
	DestLegalEntityID   pgtype.UUID        `json:"dest_legal_entity_id"`
	QuoteID             pgtype.UUID        `json:"quote_id"`
	BatchID             pgtype.UUID        `json:"batch_id"`
	RecipientID         pgtype.UUID        `json:"recipient_id"`
	IdempotencyKey      pgtype.Text        `json:"idempotency_key"`
	FromCurrency        string             `json:"from_currency"`
	ToCurrency          string             `json:"to_currency"`
	FromAmount          pgtype.Numeric     `json:"from_amount"`
	ToAmount            pgtype.Numeric     `json:"to_amount"`
	FxRate              pgtype.Numeric     `json:"fx_rate"`
	TotalFee            pgtype.Numeric     `json:"total_fee"`
	Status              TransferStatusEnum `json:"status"`
	FailureReason       pgtype.Text        `json:"failure_reason"`
	Rail                NullRailEnum       `json:"rail"`
	RailReference       pgtype.Text        `json:"rail_reference"`
	NettingGroupID      pgtype.UUID        `json:"netting_group_id"`
	IsNetted            bool               `json:"is_netted"`
	TbTransferIds       []pgtype.Numeric   `json:"tb_transfer_ids"`
	RiskScore           pgtype.Int4        `json:"risk_score"`
	ComplianceStatus    string             `json:"compliance_status"`
	ScreenedAt          pgtype.Timestamptz `json:"screened_at"`
	ComplianceRegion    string             `json:"compliance_region"`
	UpdatedAt           time.Time          `json:"updated_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

type Wallet struct {
	ID            uuid.UUID      `json:"id"`
	TenantID      uuid.UUID      `json:"tenant_id"`
	Currency      string         `json:"currency"`
	TbAccountID   pgtype.Numeric `json:"tb_account_id"`
	CachedBalance pgtype.Numeric `json:"cached_balance"`
	CachedPending pgtype.Numeric `json:"cached_pending"`
	CachedAt      time.Time      `json:"cached_at"`
	Status        string         `json:"status"`
	UpdatedAt     time.Time      `json:"updated_at"`
}
