// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	GetLegalEntityByCode(ctx context.Context, code string) (LegalEntity, error)
	GetLegalEntityByID(ctx context.Context, id uuid.UUID) (LegalEntity, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTransferByID(ctx context.Context, id uuid.UUID) (Transfer, error)
	GetTransferByIdempotencyKey(ctx context.Context, arg GetTransferByIdempotencyKeyParams) (Transfer, error)
	GetWalletByID(ctx context.Context, id uuid.UUID) (Wallet, error)
	GetWalletByTenantAndCurrency(ctx context.Context, arg GetWalletByTenantAndCurrencyParams) (Wallet, error)
	ListActiveTenants(ctx context.Context, arg ListActiveTenantsParams) ([]Tenant, error)
	ListLegalEntities(ctx context.Context) ([]LegalEntity, error)
	ListLegalEntitiesByJurisdiction(ctx context.Context, jurisdiction string) ([]LegalEntity, error)
	ListTenantsByLegalEntity(ctx context.Context, legalEntityID uuid.UUID) ([]Tenant, error)
	ListTenantsByParent(ctx context.Context, parentTenantID pgtype.UUID) ([]Tenant, error)
	ListTransfersByTenant(ctx context.Context, arg ListTransfersByTenantParams) ([]Transfer, error)
	ListTransfersByTenantAndStatus(ctx context.Context, arg ListTransfersByTenantAndStatusParams) ([]Transfer, error)
	ListWalletsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Wallet, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateTransferComplianceStatus(ctx context.Context, arg UpdateTransferComplianceStatusParams) error
	UpdateTransferNetting(ctx context.Context, arg UpdateTransferNettingParams) error
	UpdateTransferRailReference(ctx context.Context, arg UpdateTransferRailReferenceParams) error
	UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) error
	UpdateTransferTBTransferIDs(ctx context.Context, arg UpdateTransferTBTransferIDsParams) error
	UpdateWalletCachedBalance(ctx context.Context, arg UpdateWalletCachedBalanceParams) error
	UpdateWalletStatus(ctx context.Context, arg UpdateWalletStatusParams) error
}

var _ Querier = (*Queries)(nil)
