// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (tenant_id, currency, tb_account_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, currency, tb_account_id, cached_balance, cached_pending, cached_at, status, updated_at
`

type CreateWalletParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	Currency    string         `json:"currency"`
	TbAccountID pgtype.Numeric `json:"tb_account_id"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.TenantID, arg.Currency, arg.TbAccountID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Currency,
		&i.TbAccountID,
		&i.CachedBalance,
		&i.CachedPending,
		&i.CachedAt,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT id, tenant_id, currency, tb_account_id, cached_balance, cached_pending, cached_at, status, updated_at
FROM wallets
WHERE id = $1
`

func (q *Queries) GetWalletByID(ctx context.Context, id uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Currency,
		&i.TbAccountID,
		&i.CachedBalance,
		&i.CachedPending,
		&i.CachedAt,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByTenantAndCurrency = `-- name: GetWalletByTenantAndCurrency :one
SELECT id, tenant_id, currency, tb_account_id, cached_balance, cached_pending, cached_at, status, updated_at
FROM wallets
WHERE tenant_id = $1 AND currency = $2
`

type GetWalletByTenantAndCurrencyParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Currency string    `json:"currency"`
}

func (q *Queries) GetWalletByTenantAndCurrency(ctx context.Context, arg GetWalletByTenantAndCurrencyParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByTenantAndCurrency, arg.TenantID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Currency,
		&i.TbAccountID,
		&i.CachedBalance,
		&i.CachedPending,
		&i.CachedAt,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const listWalletsByTenant = `-- name: ListWalletsByTenant :many
SELECT id, tenant_id, currency, tb_account_id, cached_balance, cached_pending, cached_at, status, updated_at
FROM wallets
WHERE tenant_id = $1
ORDER BY currency
`

func (q *Queries) ListWalletsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, listWalletsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallet{}
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Currency,
			&i.TbAccountID,
			&i.CachedBalance,
			&i.CachedPending,
			&i.CachedAt,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletCachedBalance = `-- name: UpdateWalletCachedBalance :exec
UPDATE wallets
SET cached_balance = $2, cached_pending = $3, cached_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type UpdateWalletCachedBalanceParams struct {
	ID            uuid.UUID      `json:"id"`
	CachedBalance pgtype.Numeric `json:"cached_balance"`
	CachedPending pgtype.Numeric `json:"cached_pending"`
}

func (q *Queries) UpdateWalletCachedBalance(ctx context.Context, arg UpdateWalletCachedBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletCachedBalance, arg.ID, arg.CachedBalance, arg.CachedPending)
	return err
}

const updateWalletStatus = `-- name: UpdateWalletStatus :exec
UPDATE wallets
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateWalletStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateWalletStatus(ctx context.Context, arg UpdateWalletStatusParams) error {
	_, err := q.db.Exec(ctx, updateWalletStatus, arg.ID, arg.Status)
	return err
}
